baseURL = 'https://tianyuxue.github.io/'
title = 'ACoder'
languageCode = 'zh-cn'
theme = "ananke"
resourceDir = "./resources"


[menu]
[[menu.main]]
  identifier = 'about'
  name = '关于我'
  pre = "<i class='fa fa-heart'></i>"
  url = '/about/'
  weight = -100
[[menu.main]]
  name = '文章'
  post = "<span class='alert'>New!</span>"
  pre = "<i class='fa fa-road'></i>"
  url = '/posts/'
  weight = -110


DefaultContentLanguage = "zh"
SectionPagesMenu = "main"
Paginate = 5 
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "jitianyu"
  favicon = "images/code.png"
  site_logo = "images/cropped-code.png"
  description = "The last theme you'll ever need. Maybe."

  background_color_class = "bg-black"
  featured_image = "images/cropped-valais-3562988_1920-2.jpg"
  cover_dimming_class = "bg-black-10"
  recent_posts_number = 3
  show_reading_time = true

[[params.ananke_socials]]
name = "github"
url = "https://github.com/tianyuxue"
